// Generated by Wrangler on Sun May 12 2024 18:28:42 GMT-0400 (hora estándar de Chile)
// by running `wrangler types`

interface Env {
	API_RESEND: "re_e69rRE1M_65Sd8gEbdyfzihsntqKWv7ui";
	FROM_RESEND: "IMSC Industrial<contacto@imscindustrial.cl>";
	TO_RESEND: "eevp88@gmail.com";
}
