// Generated by Wrangler on Wed May 15 2024 23:48:01 GMT-0400 (hora estándar de Chile)
// by running `wrangler types`

interface Env {
	API_RESEND: "re_e69rRE1M_65Sd8gEbdyfzihsntqKWv7ui";
	FROM_RESEND: "IMSC Industrial<contacto@imscindustrial.cl>";
	TO_RESEND: "eevp88@gmail.com";
}
