// Generated by Wrangler on Tue May 07 2024 20:15:59 GMT-0400 (hora estándar de Chile)
// by running `wrangler types`

interface Env {
	API_RESEND: "re_e69rRE1M_65Sd8gEbdyfzihsntqKWv7ui";
	FROM_RESEND: "IMSC Industrial<contacto@imscindustrial.cl>";
	TO_RESEND: "eevp88@gmail.com";
}
